default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: api_guarderia

test:
  <<: *default
  database: api_guarderia_test

production:
  <<: *default
  database: api_guarderia